config/routes.rb
Rails.application.routes.draw do
  root "articles#index"
# resources-Methode mappt alle coventional routes für eine collection
#von resources, zB articles, auf diese 
  resources :articles do
    #This creates comments as a nested resource within articles. 
    # This is another part of capturing the hierarchical relationship 
    # that exists between articles and comments.
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  include Visible
  # 2. Seite der Assoziation zu einem anderen Model,
  # in diesem Fall: comment.rb (hat belongs_to :article),
  # article hat has_many :comments, sind damit assoziiert.
  # dependent: dependents des articles (die kommentare), :destroy: löschen
  has_many :comments, dependent: :destroy

  # a title value must be present (String, also mind 1 ' ' character)
  validates :title, presence: true
  # a body value must be present and at least 10 characters long.
  validates :body, presence: true, length: { minimum: 10 }

end
  

app/models/comment.rb
class Comment < ApplicationRecord
  include Visible
  belongs_to :article
end

app/models/concerns/visible.rb
module Visible
  extend ActiveSupport::Concern

  VALID_STATUSES = ['public', 'private', 'archived']

  included do
    validates :status, inclusion: { in: VALID_STATUSES }
  end

  class_methods do
    def public_count
      where(status: 'public').count
    end
  end

  def archived?
    status == 'archived'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  http_basic_authenticate_with name: "marianne", password: "password", except: [:index, :show]

  def index
    @articles = Article.all
  end

#new action: show, ruft Article.find mit der id auf, die
# in routes.rb als route parameter gesetzt wurde.
# returned Article wird in der @article instanzvariable gespeichert,
# ist also von der view accessible
  def show
    @article = Article.find(params[:id])
  end

  #new instanziiert neuen article, aber speichert ihn nicht.
  # dieser neue article wird in der view benutzt, wenn die form
  # gebaut wird. 
  def new
    @article = Article.new
  end

  #create instanziiert neuen article mit parametern für titel und
  #body, versucht, diesen zu speichern. wenn speichern klappt:
  # redirected create den browser zur seite des artikels bei
  # "http://localhost:3000/articles/#{@article.id}". 
  # wenn speichern nicht klappt:
  # render new, also app/views/articles/new.htlm.erb wird gerendert
  
  def create
    #parameter: article_params unten privately definiert
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render :new
    end
  end

  # fetches article from db, stores it in @article so that it can be used
  # when building the form. renders app/views/articles/edit.html.erb by default
  def edit
    @article = Article.find(params[:id])
  end


# (re-)fetches article from db, attempts to update it with the submitted
# data filtered by article_params. 
# if successful: action redirects the browser to the article's page
# else: redisplays the form with error msgs by rendering 
# app/views/articles/edit.html.erb

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path
  end

  private
  
  def article_params
    params.require(:article).permit(:title, :body, :status)
  end

  def comment_params
    params.require(:comment).permit(:commenter, :body, :status)
  end


end

app/controllers/comments_controller.rb
# durch das nesting: mehr Komplexität hier als in ArticlesController;

class CommentsController < ApplicationController
  http_basic_authenticate_with name: "marianne", password: "password", only: :destroy
  
  def create
    #Each request for a comment has to keep track of the article 
    #to which the comment is attached, thus the initial call to the 
    #find method of the Article model to get the article in question.
    @article = Article.find(params[:article_id])
    
    #create auf @article.comments nutzen,
    # um comment zu createn und zu saven.
    # linkt automatisch comment sodass es zum jeweiligen artikel gehört.
    @comment = @article.comments.create!(comment_params)
    # danach user zurückschicken zum originalen article mit article_path(@article) helper.
    # dies ruft die show action in ArticlesController auf, die die view show.html.erb rendert.
    # dort soll der comment auftauchen, deshalb nochmal show bearbeiten.
    redirect_to article_path(@article)
  end

  # deletes comment by locating it within @article.comments collection, then removing it from the db
  # and sending us back to the show action for the article
  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>

  <div>
  <%= form.label :status %><br>
  <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
</div>


<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", article: @article %>

app/views/articles/index.html.erb
<h1>Articles</h1>

Our blog has <%= Article.public_count %> articles and counting!
<ul>

  <% @articles.each do |article| %>
  
    <% unless article.archived? %>
 
      <li>
        <%= link_to article.title, article %>
      </li>
    <%end %>
  <% end %>
</ul>


<%= link_to "New Article", new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%# nutzt jetzt nur render statt allem, 
    was auch im partial _form.html.erb drinsteht %>
<%= render "form", article: @article %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<p><%= @article.body %></p>

<%# link zum Editen auf jeweiliger Article Seite: %>
<ul>
  <li><%= link_to "Edit this Article", edit_article_path(@article) %></li>
  <%# link zum loeschen der jeweiligen article seite%>
  <li><%= link_to "Delete this Article", article_path(@article),
                  method: :delete,
                  data: { confirm: "Are you sure?" } %></li>
</ul>

<%# fügt comment der Article show page hinzu,
    zeigt commenter und comment-body %>
<h2>Comments</h2>
<%= render @article.comments %>


<%# defines partial template we want to render (comments/form).
    Rails is smart enough to spot the forward slash in that string 
    and realize that you want to render the _form.html.erb file in 
    the app/views/comments directory.%>
<h2>Add a comment:</h2>
<%= render 'comments/form' %>

<%= link_to "Back to Index", root_path %>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
  <%= link_to 'Destroy Comment', [comment.article, comment],
              method: :delete,
              data: { confirm: "Are you sure?" } %>
</p>

app/views/comments/_form.html.erb
<%= form_with model: [ @article, @article.comments.build ] do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>

  <p>
  <%= form.label :status %><br>
  <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
</p>


<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>